// RECURRING REMINDERS - the calendar the app was missing.
//
// Asked for in a note on 2026-08-04: "Set up automatic recurring reminders (like
// Google Calendar) in the backend for recurring tasks. Specifically, by next
// quarter the system should automatically remind me to file my quarterly GST
// (deadline is the 10th of Jan/Apr/Jul/Oct)." Plus the shape stated out loud:
// "birth date is 14 August" must fire every year, not once.
//
// Pure: no DOM, no Supabase, no clock reads except the `today` you pass in.
// Everything is done on YYYY-MM-DD date KEYS with integer arithmetic rather than
// Date objects, because every date bug this codebase has hit came from an
// instant being read in the wrong zone. A reminder is a calendar fact - "10 Jan"
// - not a moment, so it should never touch UTC at all.
//
// The rules, deliberately few. Anything a person actually says out loud maps to
// one of these:
//   once      - a single date ("dentist on 12 Sep")
//   daily
//   weekly    - by weekday ("every Monday")
//   monthly   - by day of month ("rent on the 5th")
//   quarterly - by day of month, anchored to a month ("GST on the 10th of
//               Jan/Apr/Jul/Oct" is month_of_year=1, day_of_month=10)
//   yearly    - by month + day ("birthday 14 August")
//
// 2026-08-06 - the modifiers a real calendar needs, on the same integer
// arithmetic, because the mirror block below cannot hold an import:
//   interval     - "every 2 weeks", "every 3 months". ANCHORED to dtstart.
//   nth_weekday  - "the 3rd Tuesday" (3), "the last Friday" (-1).
//   weekdays     - "Mon/Wed/Fri" as [1,3,5].
//   until/count  - "until 31 Dec", "the next 6 times".
//   exdates      - "except 25 Dec".  rdates - "and also 2 Oct".
//   at_time/timezone - a reminder that fires at 18:30, not just "that day".
//
// This engine is NOT taken on trust. rrule.js (the reference RFC 5545
// implementation, vendored at vendor/rrule/) is wrapped in lib/rrule-engine.mjs
// and tests/rrule-engine.test.mjs runs several thousand generated rules through
// BOTH, asserting the occurrence sequences agree. Where they disagreed, rrule.js
// was right and this file was fixed - see the comments on nextRaw's month walk,
// withinCount's cap and nextOccurrence's ruleProblem gate, each of which names
// the rule class it got wrong. Anything that LEAVES the app (.ics export, Google
// Calendar) is generated by rrule.js via lib/rrule-codec.mjs, not by this file.

// ==== REMINDERS MIRROR START (byte-identical in supabase/functions/jarvis/index.ts) ====
// Plain declarations, exported once at the end - Deno cannot import repo-relative
// lib/, so the jarvis function hosts a copy and tests/mirror-parity.test.mjs proves
// the two never drift. Do not add an import to this block.
const FREQUENCIES = ["once", "daily", "weekly", "monthly", "quarterly", "yearly"];

const DAYS_IN_MONTH = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];

function isLeapYear(y) {
  return (y % 4 === 0 && y % 100 !== 0) || y % 400 === 0;
}

function daysInMonth(year, month /* 1-12 */) {
  if (month === 2 && isLeapYear(year)) return 29;
  return DAYS_IN_MONTH[month - 1];
}

function parseKey(key) {
  const m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(String(key || ""));
  if (!m) return null;
  const y = Number(m[1]), mo = Number(m[2]), d = Number(m[3]);
  if (mo < 1 || mo > 12 || d < 1 || d > 31) return null;
  return { y, m: mo, d };
}

function toKey(y, m, d) {
  return `${String(y).padStart(4, "0")}-${String(m).padStart(2, "0")}-${String(d).padStart(2, "0")}`;
}

// A date that does not exist lands on the last day of that month rather than
// rolling into the next one. "Rent on the 31st" in February is 28 Feb, not
// 3 March, and a 29 Feb birthday is 28 Feb in a common year. Rolling forward
// would silently move a deadline PAST itself, which for a tax filing is the one
// direction that costs money.
//
// This DIVERGES from RFC 5545, where BYMONTHDAY=31 simply skips February - 11
// fires a year against our 12. lib/rrule-codec.mjs exports the clamp faithfully
// (BYMONTHDAY=28,29,30,31;BYSETPOS=-1) rather than letting an export to Google
// silently drop a deadline; see the round-trip test there.
function clampDay(year, month, day) {
  return Math.min(Math.max(1, day), daysInMonth(year, month));
}

// Day-of-week for a date key. Sakamoto, so it needs no Date object.
const SAKAMOTO = [0, 3, 2, 5, 0, 3, 5, 1, 4, 6, 2, 4];
function weekdayOf(key) {
  const p = parseKey(key);
  if (!p) return null;
  let { y, m, d } = p;
  if (m < 3) y -= 1;
  return (y + Math.floor(y / 4) - Math.floor(y / 100) + Math.floor(y / 400) + SAKAMOTO[m - 1] + d) % 7;
}

function addDays(key, delta) {
  const p = parseKey(key);
  if (!p) return null;
  let { y, m, d } = p;
  d += delta;
  while (d > daysInMonth(y, m)) { d -= daysInMonth(y, m); m += 1; if (m > 12) { m = 1; y += 1; } }
  while (d < 1) { m -= 1; if (m < 1) { m = 12; y -= 1; } d += daysInMonth(y, m); }
  return toKey(y, m, d);
}

function compareKeys(a, b) {
  return String(a) < String(b) ? -1 : String(a) > String(b) ? 1 : 0;
}

function daysBetween(from, to) {
  const a = parseKey(from), b = parseKey(to);
  if (!a || !b) return null;
  const toDays = ({ y, m, d }) => {
    let n = d;
    for (let mm = 1; mm < m; mm++) n += daysInMonth(y, mm);
    for (let yy = 1970; yy < y; yy++) n += isLeapYear(yy) ? 366 : 365;
    return n;
  };
  return toDays(b) - toDays(a);
}

// ---- rule parts ------------------------------------------------------------

// "every 2 weeks" starting WHEN? Unanchored, the answer depends on the day you
// happen to ask, which is exactly how a fortnightly reminder drifts a week.
// `dtstart` is the anchor; ruleProblem() below REFUSES a rule that needs one and
// has none rather than returning null forever with nothing said about it.
// `interval` and `count` each have a second spelling because Postgres owns the
// obvious ones: `interval` is a type name and `count` is an aggregate, so the
// columns are rule_interval / max_count (see 20260806000030). Reading both here
// is what lets a DB row be handed to the engine unmapped - and an unmapped row
// is one fewer place for the two to disagree about a date.
function ruleInterval(rule) {
  if (!rule) return 1;
  const n = Number(rule.interval != null ? rule.interval : rule.rule_interval);
  return Number.isInteger(n) && n >= 1 ? n : 1;
}

function ruleCount(rule) {
  if (!rule) return null;
  const n = Number(rule.count != null ? rule.count : rule.max_count);
  return Number.isInteger(n) && n >= 1 ? n : null;
}

// The series anchor: explicit dtstart, else the one-off's own date.
function ruleStart(rule) {
  if (!rule) return null;
  if (parseKey(rule.dtstart)) return String(rule.dtstart);
  if (parseKey(rule.on_date)) return String(rule.on_date);
  return null;
}

// Weekdays as a sorted unique 0-6 list. Accepts the scalar `weekday` (legacy),
// an ARRAY in `weekday`, or the explicit `weekdays`. Before this, a multi-weekday
// rule hit `Number([1,3,5])` -> NaN and silently returned no date at all.
function weekdayList(rule) {
  if (!rule) return [];
  const raw = rule.weekdays != null ? rule.weekdays : rule.weekday;
  const arr = Array.isArray(raw) ? raw : [raw];
  const out = [];
  for (let i = 0; i < arr.length; i++) {
    // A null is ABSENT, not Sunday. `Number(null)` is 0, and PostgREST returns
    // null for every unset column - so { freq: "weekly", weekday: null }, the
    // shape of every weekly row read back from the database, read as weekday 0.
    // ruleProblem() then reported no problem, the engine invented a series of
    // Sundays, and describeRule() read the invention back as "every Sunday". An
    // ABSENT key already gave [] because Number(undefined) is NaN; this makes
    // null and absent answer the same, which puts "weekly needs at least one
    // weekday" back on the path it was written for. "" is dropped for the same
    // reason - an empty <input> value is also Number("") === 0.
    if (arr[i] == null || arr[i] === "") continue;
    const n = Number(arr[i]);
    if (Number.isInteger(n) && n >= 0 && n <= 6 && out.indexOf(n) === -1) out.push(n);
  }
  out.sort((a, b) => a - b);
  return out;
}

// A list of date keys (exdates / rdates), sorted, deduped, garbage dropped.
function dateList(v) {
  const arr = Array.isArray(v) ? v : (v ? [v] : []);
  const out = [];
  for (let i = 0; i < arr.length; i++) {
    const k = String(arr[i] || "");
    if (parseKey(k) && out.indexOf(k) === -1) out.push(k);
  }
  out.sort();
  return out;
}

// Months since year 0, so "every 3 months from May" is one modulo.
function monthIndex(y, m) { return y * 12 + (m - 1); }

// Weeks since the Sunday of 1970-01-04 (1970-01-01 was a Thursday). Sunday-based
// to match weekdayOf, where 0 = Sunday.
function weekIndex(key) {
  const wd = weekdayOf(key);
  if (wd == null) return null;
  const sunday = addDays(key, -wd);
  const d = daysBetween("1970-01-04", sunday);
  return d == null ? null : Math.floor(d / 7);
}

// "the 3rd Tuesday" (nth 1..5) or "the last Friday" (nth -1..-5) of one month.
// Returns null when the month has no such day - a 5th Monday does not exist in
// every month, and inventing one would fire a reminder on the wrong date.
function nthWeekdayOfMonth(y, m, weekday, nth) {
  const dim = daysInMonth(y, m);
  let day;
  if (nth > 0) {
    const firstWd = weekdayOf(toKey(y, m, 1));
    day = 1 + ((weekday - firstWd + 7) % 7) + (nth - 1) * 7;
  } else {
    const lastWd = weekdayOf(toKey(y, m, dim));
    day = dim - ((lastWd - weekday + 7) % 7) + (nth + 1) * 7;
  }
  if (day < 1 || day > dim) return null;
  return toKey(y, m, day);
}

// Where inside a month this rule lands: an nth-weekday if it has one, otherwise
// the day of the month, clamped.
function dayInMonth(y, m, rule) {
  const nth = Number(rule && rule.nth_weekday);
  if (Number.isInteger(nth) && nth !== 0) {
    const wds = weekdayList(rule);
    if (!wds.length) return null;
    return nthWeekdayOfMonth(y, m, wds[0], nth);
  }
  const day = Number(rule && rule.day_of_month);
  if (!Number.isInteger(day) || day < 1 || day > 31) return null;
  return toKey(y, m, clampDay(y, m, day));
}

// "HH:MM" -> minutes past local midnight, or null. Deliberately strict: a time
// we cannot parse must not silently become midnight, which would move an 18:30
// reminder to the top of the day. Seconds are accepted and dropped because a
// Postgres `time` column comes back over PostgREST as "18:30:00".
function minutesOfDay(hhmm) {
  const m = /^(\d{1,2}):(\d{2})(?::\d{2}(?:\.\d+)?)?$/.exec(String(hhmm == null ? "" : hhmm).trim());
  if (!m) return null;
  const h = Number(m[1]), mi = Number(m[2]);
  if (h < 0 || h > 23 || mi < 0 || mi > 59) return null;
  return h * 60 + mi;
}

// Minutes past midnight -> "HH:MM". The one display form, so "18:30:00" out of
// Postgres and "18:30" out of an <input type=time> read identically everywhere.
function formatTime(mins) {
  const n = Number(mins);
  if (!Number.isFinite(n) || n < 0) return "";
  return `${String(Math.floor(n / 60) % 24).padStart(2, "0")}:${String(Math.floor(n) % 60).padStart(2, "0")}`;
}

// Why a rule cannot fire, in words, or null when it is fine. Every "returns
// null" path in the engine has a sentence here, because a rule that is stored,
// never fires, and never explains itself is the exact failure this codebase
// keeps rediscovering.
function ruleProblem(rule) {
  rule = rule || {};
  const freq = String(rule.freq || "").toLowerCase();
  if (FREQUENCIES.indexOf(freq) === -1) return `unknown frequency "${rule.freq}"`;

  const interval = ruleInterval(rule);
  const anchor = ruleStart(rule);
  const count = ruleCount(rule);
  if (interval > 1 && !anchor) return "every-N rules need a start date to count from";
  if (count != null && !anchor) return "a count needs a start date to count from";
  if (rule.dtstart != null && rule.dtstart !== "" && !parseKey(rule.dtstart)) return "dtstart must be YYYY-MM-DD";
  if (rule.until != null && rule.until !== "" && !parseKey(rule.until)) return "until must be YYYY-MM-DD";
  if (rule.at_time != null && rule.at_time !== "" && minutesOfDay(rule.at_time) == null) {
    return `"${rule.at_time}" is not a HH:MM time`;
  }

  const nth = Number(rule.nth_weekday);
  const hasNth = Number.isInteger(nth) && nth !== 0;
  if (hasNth && (nth < -5 || nth > 5)) return "nth weekday must be 1..5 or -1..-5";
  if (hasNth && !weekdayList(rule).length) return "an nth-weekday rule needs a weekday";

  if (freq === "once") return parseKey(rule.on_date) ? null : "a one-off needs a date";
  if (freq === "daily") return null;
  if (freq === "weekly") return weekdayList(rule).length ? null : "weekly needs at least one weekday";

  if (!hasNth) {
    const day = Number(rule.day_of_month);
    if (!Number.isInteger(day) || day < 1 || day > 31) return "needs a day of the month";
  }
  if (freq === "quarterly" || freq === "yearly") {
    const mo = Number(rule.month_of_year);
    const ok = Number.isInteger(mo) && mo >= 1 && mo <= 12;
    if (!ok && !anchor) return "needs an anchor month";
  }
  return null;
}

// The rule's OWN next date on or after `from`, with no exdates, rdates, until or
// count applied. nextOccurrence() layers those on top; splitting them is what
// keeps COUNT countable (it has to enumerate the raw series).
function nextRaw(rule, from) {
  const start = parseKey(from);
  if (!start) return null;
  const freq = String(rule.freq || "").toLowerCase();
  const interval = ruleInterval(rule);
  const anchor = ruleStart(rule);

  if (freq === "once") {
    if (!parseKey(rule.on_date)) return null;
    return compareKeys(rule.on_date, from) >= 0 ? String(rule.on_date) : null;
  }

  if (freq === "daily") {
    if (interval <= 1) return String(from);
    if (!anchor) return null;
    const d = daysBetween(anchor, from);
    if (d == null) return null;
    if (d <= 0) return anchor;
    const rem = d % interval;
    return rem === 0 ? String(from) : addDays(from, interval - rem);
  }

  if (freq === "weekly") {
    const wds = weekdayList(rule);
    if (!wds.length) return null;
    const anchorWeek = anchor ? weekIndex(anchor) : null;
    if (interval > 1 && anchorWeek == null) return null;
    // One full cycle plus a week of slack is always enough to find the next hit.
    const span = 7 * interval + 7;
    for (let i = 0; i < span; i++) {
      const key = addDays(from, i);
      if (!key) return null;
      if (wds.indexOf(weekdayOf(key)) === -1) continue;
      if (interval > 1) {
        const diff = weekIndex(key) - anchorWeek;
        if (diff < 0 || diff % interval !== 0) continue;
      }
      return key;
    }
    return null;
  }

  if (freq === "monthly" || freq === "quarterly" || freq === "yearly") {
    // All three are the same walk: step months at a time from an anchored phase,
    // and place a day inside whichever month qualifies.
    const step = freq === "monthly" ? interval : (freq === "quarterly" ? 3 : 12) * interval;
    // The same refusal daily and weekly already make, which this branch was
    // missing: with no anchor the phase below falls back to the month the CALLER
    // asked from, so "every 2 months" answered Jan/Mar/May when asked in January
    // and Jun/Aug/Oct when asked in June. Same rule, different dates, decided by
    // the day you happened to look - the exact drift the anchor requirement
    // exists to prevent, and ruleProblem() already said it could not fire.
    if (interval > 1 && !anchor) return null;
    const a = anchor ? parseKey(anchor) : null;
    let phaseMonth = Number(rule.month_of_year);
    if (!Number.isInteger(phaseMonth) || phaseMonth < 1 || phaseMonth > 12) {
      if (freq === "monthly") phaseMonth = a ? a.m : start.m;
      else if (a) phaseMonth = a.m;
      else return null;
    }
    // With no dtstart the phase is a bare month-of-year, which is only
    // year-independent while `step` divides 12 - guaranteed here because
    // ruleProblem() rejects interval > 1 without an anchor. Backing the anchor
    // up a year lets a January rule be reachable from the previous December.
    const anchorIdx = monthIndex(a ? a.y : start.y - 1, phaseMonth);
    let idx = monthIndex(start.y, start.m);
    if (idx < anchorIdx) idx = anchorIdx;
    // Jump straight to the next ON-PHASE month, then step whole periods. Walking
    // every month and skipping the off-phase ones spent step-1 iterations out of
    // every step, so the old budget of step*6+24 months was only six periods of
    // real search - and a month that has no such day is skipped, so the search
    // has to be able to run long. "The 5th Tuesday of February" needs a leap
    // February that starts on a Tuesday, which is thirty years out; checked
    // against rrule.js, 58 distinct nth-weekday rules returned null forever
    // instead of their real date. 500 periods is 500 years of a yearly rule and
    // still a bounded loop; the year guard keeps toKey's 4-digit padding honest.
    const off = (idx - anchorIdx) % step;
    if (off !== 0) idx += step - off;
    for (let i = 0; i < 500 && idx < 120000; i++, idx += step) {
      const key = dayInMonth(Math.floor(idx / 12), (idx % 12) + 1, rule);
      if (key && compareKeys(key, from) >= 0) return key;
    }
    return null;
  }

  return null;
}

// Is `key` inside the rule's COUNT window? RFC 5545 sizes the set with COUNT and
// THEN removes EXDATEs, so an excluded date still consumes one of the N - which
// is why this enumerates the RAW series rather than the filtered one.
function withinCount(rule, key) {
  const n = ruleCount(rule);
  if (n == null) return true;
  const anchor = ruleStart(rule);
  if (!anchor) return false;
  let cursor = anchor;
  // The cap has to cover every count the system can STORE, or the series simply
  // stops early and says nothing: reminders.max_count is checked 1..400 in the
  // DB but lib/schedule-args.mjs clamps a scheduled task's count to 500, and at
  // a cap of 400 occurrence 401 of a count-500 rule read as "outside the count"
  // - measured against rrule.js on a plain daily rule.
  const cap = Math.min(n, 500);
  for (let i = 0; i < cap; i++) {
    const cand = nextRaw(rule, cursor);
    if (!cand) return false;
    if (cand === key) return true;
    if (compareKeys(cand, key) > 0) return false;
    cursor = addDays(cand, 1);
    if (!cursor) return false;
  }
  return false;
}

// The next date on or after `from` on which this rule fires. Returns null when
// the rule can never fire again (a `once` that has passed, a series past its
// UNTIL or COUNT) or is unusable - ruleProblem() says which, in words.
//
// `from` is inclusive: a reminder due TODAY is due today, not next year. Getting
// this backwards is how a birthday reminder fires on the 15th.
// `rule` is normalised in the body rather than via a `= {}` default: the edge
// mirror is byte-identical TypeScript, where an empty-object default infers the
// type `{}` and every property read below becomes a compile error.
function nextOccurrence(rule, from) {
  rule = rule || {};
  if (!parseKey(from)) return null;
  // ruleProblem() is the ONE authority on whether a rule can fire, so the engine
  // has to obey it rather than merely report it. Without this a rule it rejects
  // still produced dates - an unparseable `until` was ignored and the series ran
  // forever, a broken dtstart became "no anchor" and an every-N rule invented a
  // phase from the query date. A validator the engine disagrees with is worse
  // than no validator: it tells the user the rule is broken while the server
  // quietly fires it on dates nobody chose.
  if (ruleProblem(rule)) return null;
  const anchor = ruleStart(rule);
  // Nothing fires before the series starts, whatever the caller asked from.
  let cursor = (anchor && compareKeys(anchor, from) > 0) ? anchor : String(from);
  const ex = dateList(rule.exdates);
  const rd = dateList(rule.rdates);
  const until = parseKey(rule.until) ? String(rule.until) : null;

  let base = null;
  for (let i = 0; i < 64; i++) {
    const cand = nextRaw(rule, cursor);
    if (!cand) break;
    if (ex.indexOf(cand) === -1) { base = cand; break; }
    cursor = addDays(cand, 1);
    if (!cursor) break;
  }
  if (base != null && until && compareKeys(base, until) > 0) base = null;
  if (base != null && !withinCount(rule, base)) base = null;

  // RDATEs are ADDED to the set, independent of COUNT and UNTIL - an explicit
  // date is the user saying "and also this one", not part of the pattern.
  let extra = null;
  for (let i = 0; i < rd.length; i++) {
    if (compareKeys(rd[i], from) < 0) continue;
    if (ex.indexOf(rd[i]) !== -1) continue;
    extra = rd[i];
    break;
  }
  if (base == null) return extra;
  if (extra == null) return base;
  return compareKeys(extra, base) < 0 ? extra : base;
}

// Every occurrence in [from, to], capped. Powers the calendar month grid and the
// agenda list (src/ui/calendar-panel.js).
function occurrencesBetween(rule, from, to, cap = 24) {
  rule = rule || {};
  const out = [];
  let cursor = from;
  for (let i = 0; i < cap; i++) {
    const next = nextOccurrence(rule, cursor);
    if (!next || compareKeys(next, to) > 0) break;
    out.push(next);
    cursor = addDays(next, 1);
    if (!cursor) break;
  }
  return out;
}

// The IDENTITY of one firing. The server claims a fire by INSERTing this key
// into reminder_fires, so an on-device scheduler and the edge function must
// derive the same string from the same code - which is the whole reason it lives
// inside the mirror block rather than next to the caller.
//
// The timezone is deliberately NOT part of the key: moving zones does not turn
// "the 10th at 09:00" into a different occurrence, it only moves the instant.
// Without a time this is just the date key, so every row written before at_time
// existed keys exactly as it always did.
function occurrenceKey(rule, dateKey, atTime) {
  if (!parseKey(dateKey)) return null;
  const raw = (atTime != null && atTime !== "") ? atTime : (rule ? rule.at_time : null);
  const mins = minutesOfDay(raw);
  if (mins == null) return String(dateKey);
  return `${dateKey}T${String(Math.floor(mins / 60)).padStart(2, "0")}:${String(mins % 60).padStart(2, "0")}`;
}

// How a rule reads to a human. Shown in the UI and spoken in the brief, so it
// must never say something the rule does not mean.
const MONTHS = ["January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"];
const WEEKDAYS = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

function ordinal(n) {
  const s = ["th", "st", "nd", "rd"], v = n % 100;
  return n + (s[(v - 20) % 10] || s[v] || s[0]);
}

// "every 2nd week", "every 3rd month" - the plain-English form of an interval.
function everyN(n, unit) {
  return n <= 1 ? `every ${unit}` : `every ${ordinal(n)} ${unit}`;
}

function hasNthWeekday(rule) {
  const nth = Number(rule && rule.nth_weekday);
  return Number.isInteger(nth) && nth !== 0;
}

// The day-inside-the-month clause, shared by monthly/quarterly/yearly. No
// leading article - the call sites add "the" where their sentence wants one.
function describeDayPart(rule) {
  if (hasNthWeekday(rule)) {
    const nth = Number(rule.nth_weekday);
    const name = WEEKDAYS[weekdayList(rule)[0]] || "day";
    return nth < 0 ? `last ${name}` : `${ordinal(nth)} ${name}`;
  }
  return ordinal(Number(rule.day_of_month));
}

function describeRule(rule) {
  rule = rule || {};
  const freq = String(rule.freq || "").toLowerCase();
  const anchor = Number(rule.month_of_year);
  const n = ruleInterval(rule);
  let base = "";

  if (freq === "once") base = rule.on_date ? `once on ${rule.on_date}` : "once";
  else if (freq === "daily") base = n <= 1 ? "every day" : `every ${n} days`;
  else if (freq === "weekly") {
    const wds = weekdayList(rule);
    const names = wds.map((w) => WEEKDAYS[w]);
    if (!names.length) base = everyN(n, "week");
    else if (n <= 1) base = `every ${names.join(", ")}`;
    else base = `${names.join(", ")}, ${everyN(n, "week")}`;
  } else if (freq === "monthly") {
    base = n <= 1 ? `the ${describeDayPart(rule)} of every month` : `the ${describeDayPart(rule)} of ${everyN(n, "month")}`;
  } else if (freq === "yearly") {
    const mo = MONTHS[anchor - 1] || "";
    const day = hasNthWeekday(rule) ? `${describeDayPart(rule)} of ${mo}` : `${describeDayPart(rule)} ${mo}`;
    base = n <= 1 ? `every ${day}`.trim() : `${day}, ${everyN(n, "year")}`.trim();
  } else if (freq === "quarterly") {
    const step = 3 * n;
    const months = [];
    for (let m = ((anchor - 1) % step) + 1; m <= 12; m += step) months.push(MONTHS[m - 1].slice(0, 3));
    // A named month list is only TRUE while the step divides the year. Every 9
    // months from January is Jan, Oct, Jul, Apr, Jan… - it rotates - so calling
    // it "the 10th of Jan/Oct" names two months that are right the first year
    // and wrong every year after. Say the interval instead when it does not fit.
    base = months.length > 1 && 12 % step === 0
      ? `the ${describeDayPart(rule)} of ${months.join("/")}`
      : `the ${describeDayPart(rule)}, ${everyN(step, "month")}`;
  } else return "";

  // Modifiers, appended in the order a person would say them.
  const at = minutesOfDay(rule.at_time);
  if (at != null) base += ` at ${formatTime(at)}`;
  const count = ruleCount(rule);
  if (count != null) base += `, ${count} time${count === 1 ? "" : "s"}`;
  if (parseKey(rule.until)) base += `, until ${rule.until}`;
  const ex = dateList(rule.exdates);
  if (ex.length) base += `, except ${ex.join(", ")}`;
  const rd = dateList(rule.rdates);
  if (rd.length) base += `, plus ${rd.join(", ")}`;
  return base;
}

// Reminders that should be SAID today: due today, or inside their lead window.
// `lead_days` is how many days of warning a thing needs - a tax filing wants a
// week, a birthday wants a day or two - and 0 means "only on the day".
//
// Each row carries `occurrence_key`, the claim the caller inserts into
// reminder_fires. Computing it here rather than at the call site is what keeps
// the brief, the minute runner and any on-device scheduler agreeing on which
// firing they are talking about.
function dueReminders(reminders, today, { horizon = null } = {}) {
  reminders = reminders || [];
  const out = [];
  for (const r of reminders) {
    if (!r || r.active === false) continue;
    const next = nextOccurrence(r, today);
    if (!next) continue;
    const away = daysBetween(today, next);
    if (away == null) continue;
    const lead = horizon == null ? Math.max(0, Number(r.lead_days) || 0) : horizon;
    if (away > lead) continue;
    out.push({ ...r, next_due_on: next, days_away: away, occurrence_key: occurrenceKey(r, next, null) });
  }
  return out.sort((a, b) => compareKeys(a.next_due_on, b.next_due_on) || String(a.title).localeCompare(String(b.title)));
}

// Reminders whose TIME has arrived today, for the minute-resolution runner.
// `minutesNow` is minutes past local midnight in the reminder's own zone.
//
// A reminder with no at_time is NOT here: it belongs to the 07:00 brief, and
// firing it again at some arbitrary minute would be the same message twice.
// The window is one-sided (fire at or after the time, never before) and the
// caller's reminder_fires claim is what stops a late run from re-firing it.
function timedDue(reminders, today, minutesNow, { graceMinutes = 180 } = {}) {
  reminders = reminders || [];
  const now = Number(minutesNow);
  const out = [];
  if (!Number.isFinite(now)) return out;
  for (const r of reminders) {
    if (!r || r.active === false) continue;
    const at = minutesOfDay(r.at_time);
    if (at == null) continue;
    if (now < at || now - at > graceMinutes) continue;
    const next = nextOccurrence(r, today);
    if (next !== today) continue;
    out.push({ ...r, next_due_on: next, days_away: 0, at_minutes: at, occurrence_key: occurrenceKey(r, next, null) });
  }
  return out.sort((a, b) => a.at_minutes - b.at_minutes || String(a.title).localeCompare(String(b.title)));
}

// The next occurrence of every active reminder, soonest first. Powers the
// "Coming up" list. Unlike dueReminders this ignores lead_days.
function upcoming(reminders, today, { limit = 5, withinDays = 400 } = {}) {
  reminders = reminders || [];
  const out = [];
  for (const r of reminders) {
    if (!r || r.active === false) continue;
    const next = nextOccurrence(r, today);
    if (!next) continue;
    const away = daysBetween(today, next);
    if (away == null || away > withinDays) continue;
    out.push({ ...r, next_due_on: next, days_away: away, occurrence_key: occurrenceKey(r, next, null) });
  }
  out.sort((a, b) => compareKeys(a.next_due_on, b.next_due_on) || String(a.title).localeCompare(String(b.title)));
  return out.slice(0, limit);
}

// Every occurrence of every reminder inside [from, to], flattened into one
// date-keyed map: { "2026-08-14": [reminder, …] }. This is the calendar month
// grid and the agenda in one call - the UI does no date maths of its own.
function agendaBetween(reminders, from, to, { capPerRule = 64 } = {}) {
  reminders = reminders || [];
  const byDay = {};
  for (const r of reminders) {
    if (!r || r.active === false) continue;
    const days = occurrencesBetween(r, from, to, capPerRule);
    for (let i = 0; i < days.length; i++) {
      const k = days[i];
      if (!byDay[k]) byDay[k] = [];
      byDay[k].push({ ...r, next_due_on: k, occurrence_key: occurrenceKey(r, k, null) });
    }
  }
  const keys = Object.keys(byDay).sort();
  for (let i = 0; i < keys.length; i++) {
    byDay[keys[i]].sort((a, b) => {
      const am = minutesOfDay(a.at_time), bm = minutesOfDay(b.at_time);
      if (am != null && bm != null && am !== bm) return am - bm;
      if (am != null && bm == null) return -1;
      if (am == null && bm != null) return 1;
      return String(a.title).localeCompare(String(b.title));
    });
  }
  return byDay;
}

// "today", "tomorrow", "in 3 days", "in 2 weeks" - the phrasing the brief uses.
function whenLabel(daysAway) {
  const n = Number(daysAway);
  if (!Number.isFinite(n)) return "";
  if (n === 0) return "today";
  if (n === 1) return "tomorrow";
  if (n < 14) return `in ${n} days`;
  if (n < 60) return `in ${Math.round(n / 7)} weeks`;
  return `in ${Math.round(n / 30)} months`;
}

// One line per due reminder, for the morning brief and the push body.
function reminderLines(due) {
  due = due || [];
  return due.map((r) => {
    const when = whenLabel(r.days_away);
    const mins = minutesOfDay(r.at_time);
    const at = mins == null ? "" : ` at ${formatTime(mins)}`;
    return `${r.title} ${when === "today" ? "is due today" : `is due ${when}`}${at} (${r.next_due_on}).`;
  });
}
// ==== REMINDERS MIRROR END ====

export {
  FREQUENCIES,
  isLeapYear,
  daysInMonth,
  parseKey,
  toKey,
  clampDay,
  weekdayOf,
  addDays,
  compareKeys,
  daysBetween,
  ruleInterval,
  ruleCount,
  ruleStart,
  weekdayList,
  dateList,
  monthIndex,
  weekIndex,
  nthWeekdayOfMonth,
  dayInMonth,
  minutesOfDay,
  formatTime,
  ruleProblem,
  nextRaw,
  nextOccurrence,
  occurrencesBetween,
  occurrenceKey,
  describeRule,
  dueReminders,
  timedDue,
  upcoming,
  agendaBetween,
  whenLabel,
  reminderLines,
};
